/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "gwpasan_collector.h"

#include <cstdint>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fcntl.h>
#include <mutex>
#include <sys/time.h>
#include <unistd.h>
#include <vector>

#include "bundle_mgr_client.h"
#include "faultlog_util.h"
#include "file_util.h"
#include "hilog/log.h"
#include "hisysevent.h"

static std::stringstream g_asanlog;
void WriteGwpAsanLog(char* buf, size_t sz)
{
    if (buf == nullptr || sz == 0) {
        return;
    }

    static std::mutex sMutex;
    std::lock_guard<std::mutex> lock(sMutex);
    // append to buffer
    for (int i = 0; i < sz; i++) {
        g_asanlog << buf[i];
    }

    auto output = strstr(buf, "End GWP-ASan report");
    if (output) {
        std::string asanlog = g_asanlog.str();
        // parse log
        OHOS::HiviewDFX::ReadGwpAsanRecord(asanlog);
        // clear buffer
        g_asanlog.str("");
    }
}

namespace OHOS {
namespace HiviewDFX {
static constexpr HiLogLabel LABEL = {LOG_CORE, 0xD002D12, "Sanitizer"};

void ReadGwpAsanRecord(std::string& gwpAsanBuffer)
{
    GwpAsanCurrInfo currInfo;
    currInfo.description = gwpAsanBuffer;
    currInfo.pid = getpid();
    currInfo.uid = getuid();
    currInfo.errType = "GWP-ASAN";
    if (currInfo.uid >= 0) {
        currInfo.procName = GetApplicationNameById(currInfo.uid);
        currInfo.appVersion = GetApplicationVersion(currInfo.uid, currInfo.procName);
    }
    time_t timeNow = time(nullptr);
    uint64_t timeTmp = timeNow;
    std::string timeStr = GetFormatedTime(timeTmp);
    currInfo.happenTime = std::stoll(timeStr);

    // Do upload when data ready
    WriteCollectedData(currInfo);
    HiSysEventWrite(HiSysEvent::Domain::RELIABILITY, "ADDR_SANITIZER",
                    HiSysEvent::EventType::FAULT,
                    "MODULE", currInfo.procName,
                    "VERSION", currInfo.appVersion,
                    "REASON", currInfo.errType,
                    "PID", currInfo.pid,
                    "UID", currInfo.uid,
                    "SUMMARY", currInfo.description,
                    "HAPPEN_TIME", currInfo.happenTime);
}

bool WriteNewFile(const int32_t fd, const GwpAsanCurrInfo &currInfo)
{
    if (fd < 0) {
        return false;
    }

    OHOS::HiviewDFX::FileUtil::SaveStringToFd(fd, std::string("Generated by HiviewDFX @OpenHarmony") + "\n" +
        std::string("=================================================================\n") +
        "TIMESTAMP:" + std::to_string(currInfo.happenTime) +  "\n" +
        "Pid:" + std::to_string(currInfo.pid) + "\n" +
        "Uid:" + std::to_string(currInfo.uid) + "\n" +
        "Process name:" + currInfo.procName + "\n" +
        "Fault thread Info:\n" + currInfo.description);

    close(fd);
    return true;
}

std::string CalcCollectedLogName(const GwpAsanCurrInfo &currInfo)
{
    std::string filePath = "data/log/faultlog/faultlogger/";
    std::string prefix = "gwpasan";
    std::string name = currInfo.procName;
    if (name.find("/") != std::string::npos) {
        name = currInfo.procName.substr(currInfo.procName.find_last_of("/") + 1);
    }

    std::string fileName = "";
    fileName.append(prefix);
    fileName.append("-");
    fileName.append(name);
    fileName.append("-");
    fileName.append(std::to_string(currInfo.uid));
    fileName.append("-");
    fileName.append(std::to_string(currInfo.happenTime));

    std::string fullName = filePath + fileName;

    return fullName;
}

void WriteCollectedData(const GwpAsanCurrInfo &currInfo)
{
    std::string fullName = CalcCollectedLogName(currInfo);
    if (fullName.size() == 0) {
        return;
    }
    int32_t fd = CreateLogFile(fullName);
    if (fd < 0) {
        return;
    }
    WriteNewFile(fd, currInfo);
}

int32_t CreateLogFile(const std::string& name)
{
    int32_t fd = -1;
    if (!FileUtil::FileExists(name)) {
        HiLog::Warn(LABEL, "file %{public}s is creating now.", name.c_str());
    }
    fd = open(name.c_str(), O_CREAT | O_WRONLY | O_TRUNC);
    return fd;
}

std::string GetApplicationNameById(int32_t uid)
{
    std::string bundleName;
    AppExecFwk::BundleMgrClient client;
    if (client.GetNameForUid(uid, bundleName) != ERR_OK) {
        HiLog::Warn(LABEL, "Failed to query bundleName from bms, uid:%{public}d.", uid);
    } else {
        HiLog::Info(LABEL, "bundleName of uid:%{public}d is %{public}s", uid, bundleName.c_str());
    }
    return bundleName;
}

std::string GetApplicationVersion(int32_t uid, const std::string& bundleName)
{
    AppExecFwk::BundleInfo info;
    AppExecFwk::BundleMgrClient client;
    if (!client.GetBundleInfo(bundleName, AppExecFwk::BundleFlag::GET_BUNDLE_DEFAULT,
                              info, AppExecFwk::Constants::ALL_USERID)) {
        HiLog::Warn(LABEL, "Failed to query BundleInfo from bms, uid:%{public}d.", uid);
        return "";
    } else {
        HiLog::Info(LABEL, "The version of %{public}s is %{public}s", bundleName.c_str(),
                    info.versionName.c_str());
    }
    return info.versionName;
}
} // namespace HiviewDFX
} // namespace OHOS
